### ISSUE TITLE
下载到本地使用cnpm install安装提示成功 使用npm start/npm run dev运行均报错，求指点

### ISSUE THREAD

**Issue by loriswang** [BingBlog/vue-hotel#1]
Module build failed: Error: dlopen(/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
	/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __LINKEDIT extends to 3020620 which is past end of file 1668272
	/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __LINKEDIT extends to 3020620 which is past end of file 1668272
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by loriswang** [comment]
error  in ./src/page/index/children/City/SearchBar.vue

Module build failed: Error: dlopen(/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
	/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __LINKEDIT extends to 3020620 which is past end of file 1668272
	/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __LINKEDIT extends to 3020620 which is past end of file 1668272
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/Users/wangzhongmin/Desktop/vue-hotel-master/node_modules/.4.5.3@node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
